# https://github.com/TACC/containers_at_tacc/blob/f6aad6fdbef05238348ed1e87f1d159e8cd7b240/docs/advanced/02.multiarchitecture.rst#L331
---
name: Docker Image CI

on:
  push:

jobs:
  build_images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache 'pg-primary' Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-pg-primary-${{ matrix.pg_major }}
          key: ${{ runner.os }}-buildx-pg-primary-${{ matrix.pg_major }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-pg-primary-${{ matrix.pg_major }}-

      - name: Cache 'pg-standby' Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-pg-standby-${{ matrix.pg_major }}
          key: ${{ runner.os }}-buildx-pg-standby-${{ matrix.pg_major }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-pg-standby-${{ matrix.pg_major }}-

      - name: Build 'pg-primary' image
        uses: docker/build-push-action@v6
        with:
          context: test/integration/environ
          file: test/integration/environ/dockerfiles/pg-primary/Dockerfile
          #platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref_type == 'tag' }}
          tags: pgrwl/pg-primary-${{ matrix.pg_major }}
          build-args: |
            PG_MAJOR=${{ matrix.pg_major }}
          cache-from: type=local,src=/tmp/.buildx-cache-pg-primary-${{ matrix.pg_major }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new-pg-primary-${{ matrix.pg_major }},mode=max
          # share between jobs (https://docs.docker.com/build/ci/github-actions/share-image-jobs/)
          outputs: type=docker,dest=${{ runner.temp }}/pg-primary-${{ matrix.pg_major }}.tar

      - name: Build 'pg-standby' image
        uses: docker/build-push-action@v6
        with:
          context: test/integration/environ
          file: test/integration/environ/dockerfiles/pg-standby/Dockerfile
          #platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref_type == 'tag' }}
          tags: pgrwl/pg-standby-${{ matrix.pg_major }}
          build-args: |
            PG_MAJOR=${{ matrix.pg_major }}
          cache-from: type=local,src=/tmp/.buildx-cache-pg-standby-${{ matrix.pg_major }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new-pg-standby-${{ matrix.pg_major }},mode=max
          # share between jobs (https://docs.docker.com/build/ci/github-actions/share-image-jobs/)
          outputs: type=docker,dest=${{ runner.temp }}/pg-standby-${{ matrix.pg_major }}.tar

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      - name: Upload artifact 'pg-primary'
        uses: actions/upload-artifact@v4
        with:
          name: pg-primary-${{ matrix.pg_major }}
          path: pg-primary-${{ matrix.pg_major }}.tar

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      - name: Upload artifact 'pg-standby'
        uses: actions/upload-artifact@v4
        with:
          name: pg-standby-${{ matrix.pg_major }}
          path: pg-standby-${{ matrix.pg_major }}.tar

      - name: Move cache 'pg-primary'
        run: |
          rm -rf /tmp/.buildx-cache-pg-primary-${{ matrix.pg_major }}
          mv /tmp/.buildx-cache-new-pg-primary-${{ matrix.pg_major }} /tmp/.buildx-cache-pg-primary-${{ matrix.pg_major }}

      - name: Move cache 'pg-standby'
        run: |
          rm -rf /tmp/.buildx-cache-pg-standby-${{ matrix.pg_major }}
          mv /tmp/.buildx-cache-new-pg-standby-${{ matrix.pg_major }} /tmp/.buildx-cache-pg-standby-${{ matrix.pg_major }}

  test:
    name: Run integration tests (pg${{ matrix.pg_major }})
    runs-on: ubuntu-latest
    needs: [build_images]

    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input pg-primary-${{ matrix.pg_major }}.tar
          docker load --input pg-standby-${{ matrix.pg_major }}.tar
          docker image ls -a

# INPUTS:
#
# https://github.com/docker/build-push-action/blob/master/src/context.ts
#
# export interface Inputs {
#   'add-hosts': string[];
#   allow: string[];
#   annotations: string[];
#   attests: string[];
#   'build-args': string[];
#   'build-contexts': string[];
#   builder: string;
#   'cache-from': string[];
#   'cache-to': string[];
#   call: string;
#   'cgroup-parent': string;
#   context: string;
#   file: string;
#   labels: string[];
#   load: boolean;
#   network: string;
#   'no-cache': boolean;
#   'no-cache-filters': string[];
#   outputs: string[];
#   platforms: string[];
#   provenance: string;
#   pull: boolean;
#   push: boolean;
#   sbom: string;
#   secrets: string[];
#   'secret-envs': string[];
#   'secret-files': string[];
#   'shm-size': string;
#   ssh: string[];
#   tags: string[];
#   target: string;
#   ulimit: string[];
#   'github-token': string;
# }
