# https://github.com/TACC/containers_at_tacc/blob/f6aad6fdbef05238348ed1e87f1d159e8cd7b240/docs/advanced/02.multiarchitecture.rst#L331
---
name: Docker Image CI

on:
  push:

jobs:
  build-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build 'sshd' image
        uses: docker/build-push-action@v6
        with:
          context: test/integration/environ
          file: test/integration/environ/dockerfiles/sshd/Dockerfile
          #platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref_type == 'tag' }}
          tags: pgrwl/sshd
          build-args: PG_MAJOR=${{ matrix.pg_major }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build 'pg-standby' image
        uses: docker/build-push-action@v6
        with:
          context: test/integration/environ
          file: test/integration/environ/dockerfiles/pg-standby/Dockerfile
          #platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref_type == 'tag' }}
          tags: pgrwl/pg-standby
          build-args: PG_MAJOR=${{ matrix.pg_major }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

# INPUTS:
#
# https://github.com/docker/build-push-action/blob/master/src/context.ts
#
# export interface Inputs {
#   'add-hosts': string[];
#   allow: string[];
#   annotations: string[];
#   attests: string[];
#   'build-args': string[];
#   'build-contexts': string[];
#   builder: string;
#   'cache-from': string[];
#   'cache-to': string[];
#   call: string;
#   'cgroup-parent': string;
#   context: string;
#   file: string;
#   labels: string[];
#   load: boolean;
#   network: string;
#   'no-cache': boolean;
#   'no-cache-filters': string[];
#   outputs: string[];
#   platforms: string[];
#   provenance: string;
#   pull: boolean;
#   push: boolean;
#   sbom: string;
#   secrets: string[];
#   'secret-envs': string[];
#   'secret-files': string[];
#   'shm-size': string;
#   ssh: string[];
#   tags: string[];
#   target: string;
#   ulimit: string[];
#   'github-token': string;
# }
